In [17]:
library("RColorBrewer")
library("data.table")
library("readxl")
library("writexl")
library("stringr")
library("tidyr")
library("dplyr")
library("tidyverse")
library("rlang")

In [18]:
orig_svginfo = readRDS("../gitrepos/kinome-tree/Data/kintree.RDS")

In [ ]:
dt<-read.csv("./tempfiles/output-kdata.csv")

In [21]:
dt

   X  SYMBOL  Just_Kinase Result    HGNC_SYMBOL CRO_Kinase bin_25 bin_10
1   1 CDK3    CDK3/CYCE1  103.85340 CDK3        CDK3/CYCE1 100    100
2   2 CDK6    CDK6/CYCD3  102.91460 CDK6        CDK6/CYCD3 100    100
3   3 CDK2    CDK2/CYCA2  102.10290 CDK2        CDK2/CYCA2 100    100
4   4 CDK4    CDK4/CYCD3  100.73582 CDK4        CDK4/CYCD3 100    100
5   5 PKD1    PKD1        100.59809 PKD1        PKD1       100    100
6   6 DYRK2   DYRK2       100.04111 DYRK2       DYRK2      100    100
7   7 MAPK7   ERK5         98.69070 MAPK7       ERK5       100    100
8   8 DYRK3   DYRK3        97.99615 DYRK3       DYRK3      100    100
9   9 PKD3    PKD3         95.28954 PKD3        PKD3       100    100
10 10 CDK5    CDK5/P25     95.11848 CDK5        CDK5/P25   100    100
11 11 CDK1    CDK1/CYCB1   94.86562 CDK1        CDK1/CYCB1 100    100
12 12 ROCK2   ROCK2        94.70350 ROCK2       ROCK2      100    100
13 13 STK24   MST3         86.44842 STK24       MST3        90     90
14 14 RPS6KA3 RSK2         72.07244 RPS6KA3     RSK2        75     80
15 15 STK26   MST4         71.48551 STK26       MST4        75     80
16 16 MYLK2   SKMLCK       70.69339 MYLK2       SKMLCK      75     80
17 17 PRKCD   PKCD         68.21224 PRKCD       PKCD        75     70
18 18 MKNK2   MNK2         67.15418 MKNK2       MNK2        75     70
19 19 MKNK1   MNK1         63.62229 MKNK1       MNK1        75     70
20 20 CDK9    CDK9/CYCT1   60.45794 CDK9        CDK9/CYCT1  75     70
21 21 CLK3    CLK3         52.39962 CLK3        CLK3        75     60
22 22 GSK3B   GSK3B        52.24657 GSK3B       GSK3B       75     60
   bin_25_range bin_10_range
1  90-100       91-100
2  90-100       91-100
3  90-100       91-100
4  90-100       91-100
5  90-100       91-100
6  90-100       91-100
7  90-100       91-100
8  90-100       91-100
9  90-100       91-100
10 90-100       91-100
11 90-100       91-100
12 90-100       91-100
13 76-90        81-90
14 51-75        71-80
15 51-75        71-80
16 51-75        71-80
17 51-75        61-70
18 51-75        61-70
19 51-75        61-70
20 51-75        61-70
21 51-75        51-60
22 51-75        51-60

In [22]:
dt$HGNC_SYMBOL

 [1] "CDK3"    "CDK6"    "CDK2"    "CDK4"    "PKD1"    "DYRK2"   "MAPK7"
 [8] "DYRK3"   "PKD3"    "CDK5"    "CDK1"    "ROCK2"   "STK24"   "RPS6KA3"
[15] "STK26"   "MYLK2"   "PRKCD"   "MKNK2"   "MKNK1"   "CDK9"    "CLK3"
[22] "GSK3B"

In [24]:
df <- orig_svginfo$dataframe %>% 
        select(id.coral, id.HGNC) %>%
        merge(dt, by.x = "id.HGNC", by.y = "HGNC_SYMBOL") %>%
        mutate(KINASE = id.coral, HGNC_SYMBOL = id.HGNC) %>%
        arrange(HGNC_SYMBOL)

In [25]:
dim(df)[1]

[1] 21

In [26]:
dim(dt)[1]

[1] 22

In [27]:
dt <- dt %>% rename(id.HGNC= HGNC_SYMBOL)

In [28]:
missing <- dt %>%
        anti_join(orig_svginfo$dataframe, by = "id.HGNC")

In [29]:
missing

  X SYMBOL Just_Kinase Result    id.HGNC CRO_Kinase bin_25 bin_10 bin_25_range
1 5 PKD1   PKD1        100.59809 PKD1    PKD1       100    100    90-100
2 9 PKD3   PKD3         95.28954 PKD3    PKD3       100    100    90-100
  bin_10_range
1 91-100
2 91-100

In [30]:
orig_svginfo$dataframe %>%
    select(id.coral, id.HGNC) %>%
    merge(missing, by.x = "id.coral", by.y = "id.HGNC") %>%
    mutate(KINASE = id.coral, HGNC_SYMBOL = id.HGNC) %>%
    arrange(HGNC_SYMBOL)

  id.coral id.HGNC X SYMBOL Just_Kinase Result    CRO_Kinase bin_25 bin_10
1 PKD1     PRKD1   5 PKD1   PKD1        100.59809 PKD1       100    100
2 PKD3     PRKD3   9 PKD3   PKD3         95.28954 PKD3       100    100
  bin_25_range bin_10_range KINASE HGNC_SYMBOL
1 90-100       91-100       PKD1   PRKD1
2 90-100       91-100       PKD3   PRKD3

In [33]:
NAs = which(is.na(orig_svginfo$dataframe$kinase.subfamily))
NAs # the NAs index within the kinaste.subfamily column

  [1]   1   2   3   4  12  13  14  15  20  21  22  25  26  27  28  31  32  33
 [19]  34  37  38  39  43  44  45  46  47  48  49  52  53  54  55  56  57  58
 [37]  59  60  61  62  63  66  67  68  69  71  82  83  84  85  86  91  92  93
 [55]  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 110 111 112
 [73] 113 114 115 116 117 118 119 120 121 126 127 133 134 135 136 137 138 139
 [91] 140 141 142 143 144 145 146 147 148 149 150 157 158 159 160 161 162 163
[109] 164 165 166 167 168 170 171 172 173 176 181 182 183 184 192 193 195 196
[127] 197 198 199 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
[145] 219 222 223 225 226 227 228 232 233 234 236 237 238 239 241 242 243 244
[163] 245 246 247 248 249 250 251 252 253 254 255 256 264 265 266 267 268 270
[181] 271 278 281 282 283 290 295 298 299 300 301 302 303 304 305 306 307 308
[199] 309 310 311 312 315 316 320 321 336 340 341 342 343 344 345 349 350 351
[217] 352 353 354 355 357 358 359 369 370 371 372 373 374 375 376 377 378 379
[235] 380 381 382 383 385 386 387 388 391 392 397 398 399 400 403 404 405 406
[253] 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
[271] 433 434 435 436 437 438 439 441 443 445 447 448 449 450 451 452 453 454
[289] 458 459 464 465 466 471 472 473 474 475 476 477 479 480 481 482 483 484
[307] 485 486 487 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
[325] 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 521

In [34]:
#head(orig_svginfo$dataframe)

In [35]:
orig_svginfo$dataframe$kinase.subfamily[NAs] = "" # set to empty string and not NA

In [36]:
# remove NAs from HGNCs
NAs = which(is.na(orig_svginfo$dataframe$id.HGNC))
orig_svginfo$dataframe$id.HGNC[NAs] = ""

In [40]:
HGNC <- data.table(read_excel("../gitrepos//kinome-tree/data-input/HGNC-protein-coding-genes.xlsx"))
#setDT(HGNC)

manual_map <- data.table(read_excel("../gitrepos//kinome-tree/data-input/manual-map.xlsx"))
#setDT(manual_map)

In [44]:
colnames(HGNC)

[1] "HGNC_ID"      "SYMBOL"       "NAME"         "ALIAS_SYMBOL" "ALIAS_NAME"
[6] "PREV_SYMBOL"  "PREV_NAME"    "GENE_FAMILY"

In [76]:
# kinasedata <- data.table(readxl::read_xlsx("../../Downloads/CBS-220074_FT007843_kinome_data.xlsx"))
kinasedata <- read.csv("../../Downloads/FT007615.csv")
#kinasedata2 <- data.table(readxl::read_xlsx("../../Downloads/test4.xlsx"))
# kinasedata <- read.csv(file = "../data_files/ft007426_df.csv", stringsAsFactors = F)# %>%
                # select(KINASE, PCT_INHIBITION_AVG) %>% rename(Kinase = KINASE, Result = PCT_INHIBITION_AVG)

In [78]:
head(kinasedata, 10)

   BATCH_ID    BATCH_NUM COMPD_ID CONC EXPERIMENT_ID KINASE
1  FT007615-05 5         FT007615 100  200904        MET
2  FT007615-05 5         FT007615 100  200904        MET_L1195F
3  FT007615-05 5         FT007615 100  200904        MET_D1228Y
4  FT007615-05 5         FT007615 100  200904        MET_M1250I
5  FT007615-05 5         FT007615 100  200904        MET-TFG
6  FT007615-05 5         FT007615 100  200904        MET_D1228H
7  FT007615-05 5         FT007615 100  200904        MET_D1228N
8  FT007615-05 5         FT007615 100  200904        MET-KIF5B (Kex24Mex14)
9  FT007615-05 5         FT007615 100  200904        MET_D1228V
10 FT007615-05 5         FT007615 100  200904        MET_Y1230S
   PCT_INHIBITION_AVG TECHNOLOGY
1  99.330             Hot Spot
2  99.020             Hot Spot
3  98.955             Hot Spot
4  98.760             Hot Spot
5  98.510             Hot Spot
6  98.395             Hot Spot
7  97.520             Hot Spot
8  97.020             Hot Spot
9  96.990             Hot Spot
10 96.985             Hot Spot

In [79]:
HGNC.t <- HGNC %>%  mutate(SYMBOL_UPPER = stringr::str_to_upper(SYMBOL))
head(HGNC.t)

  HGNC_ID    SYMBOL NAME
1 HGNC:19    AANAT  aralkylamine N-acetyltransferase
2 HGNC:15886 AAR2   AAR2 splicing factor homolog
3 HGNC:33842 AARD   alanine and arginine rich domain containing protein
4 HGNC:20    AARS   alanyl-tRNA synthetase
5 HGNC:21022 AARS2  alanyl-tRNA synthetase 2, mitochondrial
6 HGNC:28417 AARSD1 alanyl-tRNA synthetase domain containing 1
  ALIAS_SYMBOL        ALIAS_NAME
1 SNAT                serotonin N-acetyltransferase
2 bA234K24.2          NA
3 LOC441376           Alanine and arginine-rich domain-containing protein
4 CMT2N|AlaRS         alanine tRNA ligase 1, cytoplasmic
5 KIAA1270|bA444E17.1 alanine tRNA ligase 2, mitochondrial
6 MGC2744             NA
  PREV_SYMBOL
1 NA
2 C20orf4
3 C8orf85
4 NA
5 AARSL
6 NA
  PREV_NAME
1 arylalkylamine N-acetyltransferase
2 chromosome 20 open reading frame 4|AAR2 splicing factor homolog (S. cerevisiae)
3 chromosome 8 open reading frame 85
4 NA
5 alanyl-tRNA synthetase like|alanyl-tRNA synthetase 2, mitochondrial (putative)
6 NA
  GENE_FAMILY                          SYMBOL_UPPER
1 GCN5 related N-acetyltransferases    AANAT
2 NA                                   AAR2
3 NA                                   AARD
4 Aminoacyl tRNA synthetases, Class II AARS
5 Aminoacyl tRNA synthetases, Class II AARS2
6 NA                                   AARSD1

In [80]:
ht <- HGNC.t %>%
    select(SYMBOL_UPPER, HGNC_ID, SYMBOL)
head(ht)

  SYMBOL_UPPER HGNC_ID    SYMBOL
1 AANAT        HGNC:19    AANAT
2 AAR2         HGNC:15886 AAR2
3 AARD         HGNC:33842 AARD
4 AARS         HGNC:20    AARS
5 AARS2        HGNC:21022 AARS2
6 AARSD1       HGNC:28417 AARSD1

In [61]:
# regex string generator to find partial matches
get_match_indices <- function(ls_sp1, ls_sp2, match_values, i) {
    lower_sp1 <- tolower(substr(ls_sp1[i], 2, nchar(ls_sp1[i])))
    first_sp1 <- substr(ls_sp1[i], 1, 1)
    sp2 <- ls_sp2[i]
    pattern = paste0("(.*[",
                       toupper(first_sp1), 
                       "|", 
                       tolower(first_sp1),
                       "]", 
                       lower_sp1,
                       ".*", sp2, ")"
                     )
    print(pattern)
    match_indices <- grep(pattern = pattern,
                          ignore.case = F, 
                          x = match_values 
                         )
    print(paste(i, ":", match_indices))
    return(match_indices)
    }

# main call to loop thru indices for a 1 index match
map_regex_match <- function(df, HGNC, i) {
    ls_sp1 <- df$sp1
    ls_sp2 <- df$sp2
    name_match_indices <- get_match_indices(ls_sp1, ls_sp2, HGNC$NAME, i)
    if (length(name_match_indices) == 1) {
        return(name_match_indices)
    } else {
        if (length(name_match_indices > 1)) {
            for (j in name_match_indices) {
                print(j)
                print(HGNC$NAME[j])
                alias_match_indices <- get_match_indices(ls_sp1, ls_sp2, HGNC$ALIAS_NAME[j], i)
                if (length(alias_match_indices) == 1) {
                    return(j)
                } else {
                    prev_match_indices <- get_match_indices(ls_sp1, ls_sp2, HGNC$PREV_NAME[j], i)
                    if (length(prev_match_indices) == 1) {
                        return(j)
                    }
                }
            }
        }
    }
    return(NA)
}

In [51]:
regex_alias <- function(the_string) {
   # rtn_ls <- list(SYMBOL = NA, HGNC_ID = NA)
   rtn_c <- c("NA", "NA") 
   if (the_string == "NA") {return(rtn_c)}
   pattern <- paste0("(?<![A-Za-z])", the_string, "(?![A-Za-z])") 
   colnames <- c("SYMBOL", "ALIAS_SYMBOL", "PREV_SYMBOL", "NAME", "PREV_NAME", "ALIAS_NAME") 
   nbr_rows <- -1
   cnt <- 1
   nbr_of_fields <- length(colnames)
    
   while (nbr_rows != 1) {
       hgnc_df <- HGNC %>%
                filter(grepl(x = !!as.name(colnames[cnt]), 
                            pattern = pattern,
                            perl = T,
                            ignore.case = T)
                       )
                    
       # print(hgnc_df)
        nbr_rows <- nrow(hgnc_df)
        if (cnt == nbr_of_fields) {break}
        cnt <- cnt + 1
   }
    
    
   if (nrow(hgnc_df) != 0) {
       rtn_c <- c(hgnc_df$SYMBOL, hgnc_df$HGNC_ID)
   }
   # rtn_ls$SYMBOL <- hgnc_df$SYMBOL
   # rtn_ls$HGNC_ID <- hgnc_df$HGNC_ID
    
   # return(rtn_ls)
   return(rtn_c)
                                 
}

In [52]:
get.hgnc.id <- function(HGNC, pattern ) {
    d <- HGNC %>% filter(grepl(x = SYMBOL, pattern = paste0("^", pattern, "$"))) %>% select(HGNC_ID) %>% pull() 
    # print(pattern)
    # print(d)
    if (length(d) > 1) {
        return("")
        }
    if (length(d) == 0) {
        return("")
        }
    return(d)
    }

In [53]:
ht <- HGNC %>%
    select(HGNC_ID, SYMBOL) %>%
    mutate(SYMBOL_UPPER = stringr::str_to_upper(SYMBOL))

In [81]:
# dd <- read.csv("/home/jovyan/work/Downloads/output-df.csv")
# dt <- read.csv("/home/jovyan/work/Downloads/output.csv")

In [82]:
dff <-
kinasedata %>% 
    select(KINASE, PCT_INHIBITION_AVG) %>%
    filter(PCT_INHIBITION_AVG >= 60,
        !grepl(pattern = "\\[", x = KINASE), 
        !grepl(pattern = "^(?!.*\\/).*\\(.*\\)$", x = KINASE, perl=T) ) %>%
    mutate(No_Greek =  case_when(
        grepl(pattern="α", KINASE) ~ gsub("α", "A", KINASE),
        grepl(pattern = "β", KINASE)  ~ gsub("β", "B", KINASE),
        grepl(pattern = "γ", KINASE) ~ gsub("γ", "G", KINASE),
        grepl(pattern = "δ", KINASE) ~ gsub("δ", "d", KINASE),
        grepl(pattern = "ᐃ" , KINASE)~ gsub("ᐃ", "D",KINASE),
        grepl(pattern = "ε" , KINASE)~ gsub("ε", "E",KINASE),
        grepl(pattern = "ζ" , KINASE)~ gsub("ζ", "Z",KINASE),
        grepl(pattern = "η" , KINASE)~ gsub("η","H", KINASE),
        grepl(pattern = "θ" , KINASE)~ gsub("θ", "Q",KINASE),
        grepl(pattern = "ι" , KINASE)~ gsub("ι", "I",KINASE),
        TRUE ~ KINASE ) ) %>%
    mutate(No_Space = str_replace(No_Greek, " ", "_"),
    Just_KINASE = sub("_.*", "", No_Space),
    Just_KINASE = stringr::str_to_upper(Just_KINASE)) %>%
    separate(No_Space, into = c('sp1', 'sp2', 'sp3'), extra = 'drop', remove = FALSE, fill="right") %>%
    merge(ht, by.x = 'Just_KINASE', by.y = 'SYMBOL_UPPER', all.x = TRUE, all.y = FALSE) %>%
    arrange(desc(PCT_INHIBITION_AVG)) %>%
    rename(Result = PCT_INHIBITION_AVG, Kinase = KINASE)

In [83]:
dtt <- dff %>% 
                filter(!is.na(sp2) | !is.na(sp3), 
                             is.na(HGNC_ID)) %>%
                mutate(INDEX = row_number())

In [ ]:
dtt

In [ ]:
regex_iterate_match(p2)

In [ ]:
get.hgnc.id(HGNC, 'AMPKA2')

In [ ]:
for (i in seq(nrow(dtt))) {
        p1 = dtt %>% filter(INDEX == i) %>% select(sp1) %>% pull()
        x1 = get.hgnc.id(HGNC, p1)
        print(paste0('x1 top: ', x1))
        if (x1 == "") {
                p2 = dtt %>% filter(INDEX == i) %>% select(sp2) %>% pull()
                x2 = get.hgnc.id(HGNC, p2)
                print(paste0('x2 top: ', x2))
                if (x2 == "") {
                    x1 <- regex_iterate_match(p1) 
                    print(paste0('x1 bottom:', x1))
                    if (is.na(x1)) {
                        x1 = regex_iterate_match(p2)
                        print(paste0('x1:', x1, ' p2: ', p2))
                    }
                    }
                else { x1 = duplicate(x2, shallow=F) }
                }
        if (i > 11) {
        print(paste0("x1:", x1, "i: ", i))
        if (!is.na(x1)) {
                tmp.symbol <- HGNC %>% filter(HGNC_ID == x1) %>% select(SYMBOL) %>% pull()
                # print(paste0("tmp:", x1))
                dd <- dd %>% mutate(HGNC_ID = replace(HGNC_ID, Result == dtt$Result[i], x1),
                               SYMBOL = replace(SYMBOL, Result == dtt$Result[i], tmp.symbol))
                }
        }
    }

In [ ]:
for (i in seq(nrow(dt))) {
        p1 = dt %>% filter(INDEX == i) %>% select(sp1) %>% pull()
        x1 = get.hgnc.id(HGNC, p1)
        print(paste0('x1 top: ', x1))
        if (x1 == "") {
                p2 = dt %>% filter(INDEX == i) %>% select(sp2) %>% pull()
                x2 = get.hgnc.id(HGNC, p2)
                print(paste0('x2 top: ', x2))
                if (x2 == "") {
                    x1 <- regex_iterate_match(p1) 
                    print(paste0('x1 bottom:', x1))
                    if (is.na(x1)) {
                        x1 = regex_iterate_match(p2)
                        print(paste0('x1:', x1, ' p2: ', p2))
                    }
                    }
                else { x1 = duplicate(x2, shallow=F) }
                }
        if (i > 11) {
        print(paste0("x1:", x1, "i: ", i))
        if (!is.na(x1)) {
                tmp.symbol <- HGNC %>% filter(HGNC_ID == x1) %>% select(SYMBOL) %>% pull()
                # print(paste0("tmp:", x1))
                dd <- dd %>% mutate(HGNC_ID = replace(HGNC_ID, Result == dt$Result[i], x1),
                               SYMBOL = replace(SYMBOL, Result == dt$Result[i], tmp.symbol))
                }
        }
    }

In [55]:
regex_iterate_match <- function(pattern) {
    colnames <- c("SYMBOL", "ALIAS_SYMBOL", "PREV_SYMBOL", "NAME", "PREV_NAME", "ALIAS_NAME") 
    rtn <- NA
    nbr_rows <- -1
    cnt <- 1
    nbr_of_fields <- length(colnames)
    pattern = paste0("(^|\\|)", pattern, "(\\||$)")

    while (nbr_rows != 1) {
       hgnc_df <- HGNC %>%
                filter(grepl(x = !!as.name(colnames[cnt]), 
                            pattern = pattern,
                            perl = T, 
                            ignore.case = T)
                       )

        # print(hgnc_df)
        nbr_rows <- nrow(hgnc_df)
        if (nbr_rows == 1) {
            return( hgnc_df$HGNC_ID)
            }
        if (cnt == nbr_of_fields) {break}
        cnt <- cnt + 1
    }
    return( rtn)
    }

In [ ]:
dd %>% filter(is.na(SYMBOL))#, !is.na(sp2), nchar(sp2) < 2)

In [84]:
df_sym_nomatch <- dff %>% 
        filter(is.na(HGNC_ID))

df_sym_match <- dff %>% 
        filter(!is.na(HGNC_ID))  

SEC_HGNC <- HGNC %>% separate_rows(ALIAS_SYMBOL, sep = "\\|") %>% 
                                        separate_rows(PREV_SYMBOL, sep = "\\|") %>%
                                        mutate(ALIAS_UPPER = stringr::str_to_upper(ALIAS_SYMBOL), 
                                                     PREV_UPPER = stringr::str_to_upper(PREV_SYMBOL))

df_sym_nomatch <- df_sym_nomatch %>%
                                mutate(HGNC_ID = NULL,
                                             SYMBOL = NULL)

In [66]:
df_sym_nomatch

     Just_KINASE Kinase Result No_Greek No_Space sp1 sp2 sp3

In [85]:
df_alias_match <- merge(df_sym_nomatch, 
                        SEC_HGNC, 
                        by.x = 'Just_KINASE', 
                        by.y = 'ALIAS_UPPER', 
                        all.x = T, 
                        all.y = F
                        )